// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJWHmJhCm1yj7T3f_9Glmmi0H0lFURl_g',
    appId: '1:870303052480:web:4427eb5b9cbea7990f7325',
    messagingSenderId: '870303052480',
    projectId: 'easylink-60d4a',
    authDomain: 'easylink-60d4a.firebaseapp.com',
    storageBucket: 'easylink-60d4a.appspot.com',
    measurementId: 'G-X3CL4YG8N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcP3RFZJN6oFeKgJJENQziX-LGYpl6jlw',
    appId: '1:870303052480:android:2d0531ffa63ac1290f7325',
    messagingSenderId: '870303052480',
    projectId: 'easylink-60d4a',
    storageBucket: 'easylink-60d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi2qRAvsgBa5v7ENKQFHacAgyHSmWWvUo',
    appId: '1:870303052480:ios:0384969f2a8f37540f7325',
    messagingSenderId: '870303052480',
    projectId: 'easylink-60d4a',
    storageBucket: 'easylink-60d4a.appspot.com',
    iosBundleId: 'com.example.easylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi2qRAvsgBa5v7ENKQFHacAgyHSmWWvUo',
    appId: '1:870303052480:ios:0384969f2a8f37540f7325',
    messagingSenderId: '870303052480',
    projectId: 'easylink-60d4a',
    storageBucket: 'easylink-60d4a.appspot.com',
    iosBundleId: 'com.example.easylink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJWHmJhCm1yj7T3f_9Glmmi0H0lFURl_g',
    appId: '1:870303052480:web:dd942e3a989df3bd0f7325',
    messagingSenderId: '870303052480',
    projectId: 'easylink-60d4a',
    authDomain: 'easylink-60d4a.firebaseapp.com',
    storageBucket: 'easylink-60d4a.appspot.com',
    measurementId: 'G-SW0WZXV2NM',
  );
}
